// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7yC8c9OuZp1sLe4mziYqD9s9kgL65JKQ',
    appId: '1:14892257053:web:715218c4d486a564281bf4',
    messagingSenderId: '14892257053',
    projectId: 'thumbhq',
    authDomain: 'thumbhq.firebaseapp.com',
    storageBucket: 'thumbhq.firebasestorage.app',
    measurementId: 'G-Y6X4P5CPNH',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2zb7QjJ4V-4Ki_MG4LscR_qyykkPJsk',
    appId: '1:14892257053:android:66b10c0659077c3c281bf4',
    messagingSenderId: '14892257053',
    projectId: 'thumbhq',
    storageBucket: 'thumbhq.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1OCidRqpDMxGETErfv6rwnBsOub_96Y',
    appId: '1:14892257053:ios:05d8efe3225f9d6b281bf4',
    messagingSenderId: '14892257053',
    projectId: 'thumbhq',
    storageBucket: 'thumbhq.firebasestorage.app',
    iosBundleId: 'com.shlabs.thumbhq',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1OCidRqpDMxGETErfv6rwnBsOub_96Y',
    appId: '1:14892257053:ios:05d8efe3225f9d6b281bf4',
    messagingSenderId: '14892257053',
    projectId: 'thumbhq',
    storageBucket: 'thumbhq.firebasestorage.app',
    iosBundleId: 'com.shlabs.thumbhq',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7yC8c9OuZp1sLe4mziYqD9s9kgL65JKQ',
    appId: '1:14892257053:web:a9f27cbf7b99bb47281bf4',
    messagingSenderId: '14892257053',
    projectId: 'thumbhq',
    authDomain: 'thumbhq.firebaseapp.com',
    storageBucket: 'thumbhq.firebasestorage.app',
    measurementId: 'G-9BV1Z7HKN1',
  );
}
